---
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
spec:
   containers:
    - name: website
      image: nginx:stable-alpine
      command: [ "nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;" ]
      ports:
        - containerPort: 80
      volumeMounts:
       - mountPath: "/web-data"
         name: web-data
       - mountPath: /etc/nginx/nginx.conf
         subPath: nginx.conf
         name: nginx-config
   initContainers:
    - name: init-html-data
      image: busybox:1.31.1
      command: [ "wget", "-O", "/web-data/index.html", "http://raw.githubusercontent.com/km4rcus/opennebula-firework-example/master/html/index.html" ]
      volumeMounts:
       - mountPath: "/web-data"
         name: web-data

   volumes:
    - name: web-data
      persistentVolumeClaim:
        claimName: web-data-claim
    - name: nginx-config
      configMap:
        name: nginx-config
